apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "your_email@gmail.com"
  GMAIL_PASSWORD: "16-characters password after switching on MFA from Google settings"
type: Opaque